-- ============================================================================
-- Postgres schema for the SQL practice database (prep).
-- Load with:   psql ... -d prep -f schema.sql -f seed.sql
-- (seed.sql is generated by build_db.py — run `python3 build_db.py` first.)
-- ============================================================================
DROP TABLE IF EXISTS usage_metrics, cost_records, incidents,
                     deployments, servers, services, data_centers, regions CASCADE;

CREATE TABLE regions (
    region_id   INTEGER PRIMARY KEY,
    name        TEXT NOT NULL,
    country     TEXT NOT NULL
);

CREATE TABLE data_centers (
    dc_id            INTEGER PRIMARY KEY,
    region_id        INTEGER NOT NULL REFERENCES regions(region_id),
    name             TEXT NOT NULL,
    capacity_cores   INTEGER NOT NULL,
    opened_date      DATE NOT NULL
);

CREATE TABLE services (
    service_id   INTEGER PRIMARY KEY,
    name         TEXT NOT NULL,
    team         TEXT NOT NULL,
    tier         TEXT NOT NULL            -- 'critical' | 'standard' | 'batch'
);

CREATE TABLE servers (
    server_id          INTEGER PRIMARY KEY,
    dc_id              INTEGER NOT NULL REFERENCES data_centers(dc_id),
    server_type        TEXT NOT NULL,     -- 'compute' | 'storage' | 'gpu'
    cores              INTEGER NOT NULL,
    memory_gb          INTEGER NOT NULL,
    hourly_cost_usd    NUMERIC(10,3) NOT NULL,
    commissioned_date  DATE NOT NULL,
    status             TEXT NOT NULL      -- 'active' | 'idle' | 'retired'
);

CREATE TABLE deployments (
    deployment_id  INTEGER PRIMARY KEY,
    service_id     INTEGER NOT NULL REFERENCES services(service_id),
    server_id      INTEGER NOT NULL REFERENCES servers(server_id),
    start_date     DATE NOT NULL,
    end_date       DATE                   -- NULL = still active
);

CREATE TABLE usage_metrics (
    metric_date  DATE NOT NULL,
    server_id    INTEGER NOT NULL REFERENCES servers(server_id),
    cpu_util     DOUBLE PRECISION NOT NULL,   -- 0..1
    mem_util     DOUBLE PRECISION NOT NULL,   -- 0..1
    requests     INTEGER NOT NULL,
    PRIMARY KEY (metric_date, server_id)
);

CREATE TABLE cost_records (
    cost_date    DATE NOT NULL,
    server_id    INTEGER NOT NULL REFERENCES servers(server_id),
    cost_usd     NUMERIC(12,2) NOT NULL,
    PRIMARY KEY (cost_date, server_id)
);

CREATE TABLE incidents (
    incident_id   INTEGER PRIMARY KEY,
    service_id    INTEGER NOT NULL REFERENCES services(service_id),
    severity      INTEGER NOT NULL,      -- 1 (worst) .. 4
    opened_date   DATE NOT NULL,
    resolved_date DATE                   -- NULL = still open
);
